import os
import torch
# AWS configuration (read from environment, not hardcoded!)
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID","AKIA5G2VGIXXKHHEUDD3")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY","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")
AWS_DEFAULT_REGION = os.getenv("AWS_DEFAULT_REGION", "ap-south-1")
AWS_BUCKET = os.getenv("AWS_BUCKET", "kclwebsitebucket")
# S3 Base URL
AWS_URL = f"https://{AWS_BUCKET}.s3.amazonaws.com"

INDEX_FILE = "tile_index.pkl"  # generated by reindex.py
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Local fallback
LOCAL_TILE_FOLDER = os.getenv("LOCAL_TILE_FOLDER", "static/tiles")

# Uploads (user query images)
UPLOAD_FOLDER = "uploads"
MAX_CONTENT_LENGTH = 5 * 1024 * 1024  # 5 MB
ALLOWED_EXTENSIONS = {"png", "jpg", "jpeg"}
MATCH_THRESHOLD = 0.9  # 90% similarity

